version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: hestia-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hestia

volumes:
  mongo_data:
